name: Publish deb to Release

on:
    push:
      tags:
        - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
      permissions:
        contents: write
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: deb
            path: .

        - name: Release deb
          uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            prerelease: false
            files: |
                *.deb
